### ISSUE TITLE
Greta in Android using Unity

### ISSUE THREAD

**Issue by mariomor** [isir/greta#36]
Hi,

I have Greta + Unity working just fine on my laptop.
From Unity, I generated an APK and have installed in my Samsung S5. My laptop and S5 are both connected to my LAN via WiFi and Thrift Command receiver and BAP/FAP, well connected at Modular.

When I run an FML example (welcome) I can see Greta executing the instructions (FAP/BAP). The problem is that just 1 in 100 attempts she can execute the script comprehensively. The majority of the attempts she does it partially (i.e. FAP/BAP starts but then get frozen) or simply nothing happens.
I have checked the code both at Server (Greta) and Client (Unity) sides and did not found anything relevant to improve the performance. Thrift also apparently has no issues.
In my successful attempt, I ran the FML script, say 20 times in a row, and always successfully. But after stopping and restarting again with same configuration, it never performed well again.

I am wonder if the problem lies on S5 CPU/Mem performance since in the laptop I never faced any issue. But then, when I remember that I was able to run it smoothly once, I get puzzled.

Any clues in how to improve the perform of Uinity client when running in Android mobile devices?

Br,
Mario.

**Comment by mariomor** [comment]
By changing ANIM_DELAY from 0 to 1000, it helps. But the root cause of the issue is not necessarily the wifi latency.
Thrift some times its fast sending messages to the client and some other times it is not. I am not (yet) convinced that this change of behavior is due to the LAN wifi. There is no apparent reason to this to happen whem I have only 2 devices connected to the same LAN via Wifi.
Nevertheless, when Thrift is slow dispatching the messages, the problem comes. When it is fast, the animation on unity client side, works just fine.

**Comment by sagatake** [comment]
Sorry for this very late response. We recognize that this problem of undeliverable signals (even on laptops) when we use ActiveMQ or Thrift. At this moment, we have not found any solution yet. We close this issue but we continue to investigate this.
