### ISSUE TITLE
BML parser crashes if the word is only "a" (which is common in English)

### ISSUE THREAD

**Issue by fajrian-yunus-isir-upmc** [isir/greta#38]
I am using OpenMary (not sure if it is related)

**Comment by PhilGauthier** [comment]
Hi @fajrian-yunus-isir-upmc, do you have a sample file to reproduce the issue ?

**Comment by fajrian-yunus-isir-upmc** [comment]
Here it is. This BML does NOT work:
```
<bml>
<speech id="s1" language="english" start="0.0" text="" type="SAPI4" voice="marytts" xmlns="">
<description level="1" type="gretabml"><reference>tmp/from-fml-apml.pho</reference></description>
<tm id="tm0"/>I 
<tm id="tm1"/>am 
<tm id="tm2"/>eating 
<tm id="tm3"/>a 
<tm id="tm4"/>donut 
<tm id="tm5"/>
</speech>
</bml>
```

But this BML works:
```
<bml>
<speech id="s1" language="english" start="0.0" text="" type="SAPI4" voice="marytts" xmlns="">
<description level="1" type="gretabml"><reference>tmp/from-fml-apml.pho</reference></description>
<tm id="tm0"/>I 
<tm id="tm1"/>am 
<tm id="tm2"/>eating 
<tm id="tm3"/>aa 
<tm id="tm4"/>donut 
<tm id="tm5"/>
</speech>
</bml>
```

The difference is the word after `<tm id="tm3"/>`

**Comment by PhilGauthier** [comment]
Hum, both works for me.
I used this to feed the fml file reader :
```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<fml-apml>
	<bml>
		<speech id="s1" language="english" start="0.0" text="" type="SAPI4" voice="marytts" xmlns="">
			<description level="1" type="gretabml"><reference>tmp/from-fml-apml.pho</reference></description>
			<tm id="tm0"/>I
			<tm id="tm1"/>am
			<tm id="tm2"/>eating
			<tm id="tm3"/>a
			<tm id="tm4"/>donut
		</speech>
	</bml>	
</fml-apml>
```
I used the "Basic Configuration", with Github's master branch version of Greta, marytts-5.1, Java 1.8.0_241
Did you do something different ? 
You get a java Exception ?

**Comment by fajrian-yunus-isir-upmc** [comment]
There is no exception (and the program does not crash, actually). But the agent does nothing. When I changed "a" into "aa", then the agent speaks.

**Comment by fajrian-yunus-isir-upmc** [comment]
Anyway, I am using marytts-5.2 and java 1.8.0_172.

**Comment by fajrian-yunus-isir-upmc** [comment]
The voice I tried with marytts-5.2 was en-US and cmu-slt

**Comment by fajrian-yunus-isir-upmc** [comment]
I just tried with marytts-5.1 and the voice was en-US and cmu-slt-hsmm, now the FML works. So I think it depends on the marytts version and the voice we use.
