### ISSUE TITLE
What is supported?

### ISSUE THREAD

**Issue by toncho11** [isir/greta#39]
Hi,

Would you please answer me these questions:

So Greta is using Unity to visualize the 3D character?
Can Greta's speech be annotated with SSML (Speech Synthesis Markup Language )? 
Does Greta includes a decision making system or some kind of inference or intelligence engine?
Do you use any probabilistic models?

**Comment by gretaproject** [comment]
Hello,

to visualize 3D characters, you can use the animation player built in Greta (using OpenGL) or Unity3D.
Greta does not make use of SSML yet. However you can use SSML with a speech synthesizer that recognizes it.
Greta can be linked to several modules that can act at a decision making system. For example, it can be linked to FaTiMa, emotion model (https://github.com/GAIPS-INESC-ID/FAtiMA-Toolkit) or to the dialog system Flipper (https://github.com/hmi-utwente/Flipper-2.0).
I am not sure to understand your last question: to which models do you refer to?

**Comment by toncho11** [comment]
Thank you.
I mean probabilistic models such as Bayesian nets.

**Comment by gretaproject** [comment]
We are using a large variety of approaches to compute non-verbal behaviors, ranging from rule-based to sequence mining.
