### ISSUE TITLE
Generate a video with openface animation

### ISSUE THREAD

**Issue by aldelb** [isir/greta#42]
Hello,

I use GRETA to animate a virtual agent with a csv file in openface format. I succeed to animate the agent from these csv files (generated before and not in real time, so I use the openface 1 module) but I can't find how to save the video of this animation ? I would like to either record a video that has exactly the same duration as the openface timestamps or add using greta a .wav file that corresponds to the character's voice and then generate the video.

Do you know if it's possible? And what modules should I use for that?

Thank you in advance for your answer.

Best regards.

Alice Delbosc

**Comment by aldelb** [comment]
update : I found the xuggle module in the branch gpl. So my video is generated from the csv openface, but without any sound.

**Comment by PhilGauthier** [comment]
Hi @aldelb 
Yes, for the moment we only have the Xuggle module to record the video and audio is missing.
An other option is to use https://obsproject.com/ but then it we be harder to track regarding to the input openface timestamps.
